# -*- coding: utf-8 -*-
"""Translate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-DNMQYdiUIfH9YulhU0f_f8BoS_8I1ni
"""

from transformers import pipeline, M2M100ForConditionalGeneration, M2M100Tokenizer

lang_detect = pipeline(
    "text-classification",
    model="papluca/xlm-roberta-base-language-detection"
)

model_name = "facebook/m2m100_418M"
tokenizer = M2M100Tokenizer.from_pretrained(model_name)
translator = M2M100ForConditionalGeneration.from_pretrained(model_name)

iso_to_full = {
    "en": "English",
    "es": "Spanish",
    "fr": "French",
    "de": "German",
    "it": "Italian",
    "pt": "Portuguese",
    "ru": "Russian",
    "zh": "Chinese",
    "ja": "Japanese",
    "ko": "Korean",
    "ar": "Arabic",
    "hi": "Hindi",
    "th": "Thai",
    "nl": "Dutch",
    "sv": "Swedish",
    "fi": "Finnish",
    "tr": "Turkish",
    "pl": "Polish",
    "uk": "Ukrainian",
    "vi": "Vietnamese"
}

def detect_language(text):       #Detect the language code of a sentence

    pred = lang_detect(text)[0]   # get the top prediction
    code = pred['label'].replace("lang_", "")  # remove prefix if present
    return code

def translate_to_english(text, src_lang):         #Translate text from detected language to English.

  tokenizer.src_lang = src_lang                 #tell the tokenizer the source language
  encoded = tokenizer(text, return_tensors="pt")  #encode the text
  generated_tokens = translator.generate(
      **encoded,
      forced_bos_token_id=tokenizer.get_lang_id("en")  #translation to engilish
  )
  return tokenizer.decode(generated_tokens[0], skip_special_tokens=True)

samples = [
    "Bonjour tout le monde",  # French
    "Hola, ¿cómo estás?",     # Spanish
    "こんにちは",                # Japanese
    "Hello, how are you?",     # English
    "Wie geht es dir?",        # German
    "नमस्ते, आप कैसे हैं?",       # Hindi
]

for text in samples:
    code = detect_language(text)
    full_lang = iso_to_full.get(code, code)
    translated = translate_to_english(text, code)
    print(f"Input: {text}")
    print(f"Detected Language: {full_lang} ({code})")
    print(f"Translated to English: {translated}\n")